### ISSUE TITLE
Update TO Add Import Export

### ISSUE THREAD

**Issue by becega** [LabVIEW-DCAF/PIDModule#14]

**Comment by jacobson3** [comment]
@becega the latest commit added this feature but I'm going to tag it again because the export feature doesn't seem to work correctly. it looks like the Setpoint channel exports correctly, the Variable and Output channels don't export anything, and the rest export default values.

Change the attached .txt to .pcfg and that is the config I used to test the export functionality.


[Test.txt](https://github.com/LabVIEW-DCAF/PIDModule/files/2506700/Test.txt)
